import { boolean, date, decimal, int, json, mysqlEnum, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(), openId: varchar("openId", { length: 64 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), loginMethod: varchar("loginMethod", { length: 64 }), role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});
export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

const businessRoles = ["admin", "sales", "tailor", "inventory", "payroll"] as const;
export type BusinessRole = (typeof businessRoles)[number];
export const userBusinessRoles = mysqlTable("userBusinessRoles", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull().unique(), role: mysqlEnum("role", businessRoles).notNull().default("sales"), isActive: boolean("isActive").notNull().default(true), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const customRoles = mysqlTable("customRoles", { id: int("id").autoincrement().primaryKey(), name: varchar("name", { length: 80 }).notNull().unique(), description: varchar("description", { length: 320 }), permissionsJson: json("permissionsJson").notNull(), isActive: boolean("isActive").notNull().default(true), createdBy: int("createdBy").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const userCustomRoles = mysqlTable("userCustomRoles", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull().unique(), customRoleId: int("customRoleId").notNull(), isActive: boolean("isActive").notNull().default(true), updatedBy: int("updatedBy").notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const shopSettings = mysqlTable("shopSettings", { id: int("id").autoincrement().primaryKey(), shopName: varchar("shopName", { length: 160 }).notNull(), arabicShopName: varchar("arabicShopName", { length: 160 }), crNumber: varchar("crNumber", { length: 80 }), currency: varchar("currency", { length: 8 }).notNull().default("BHD"), phone: varchar("phone", { length: 50 }), email: varchar("email", { length: 320 }), address: text("address"), invoicePrefix: varchar("invoicePrefix", { length: 16 }).notNull().default("INV"), updatedBy: int("updatedBy"), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const customers = mysqlTable("customers", { id: int("id").autoincrement().primaryKey(), name: varchar("name", { length: 160 }).notNull(), phone: varchar("phone", { length: 50 }).notNull(), email: varchar("email", { length: 320 }), address: text("address"), notes: text("notes"), preferredContact: varchar("preferredContact", { length: 40 }), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const measurementProfiles = mysqlTable("measurementProfiles", { id: int("id").autoincrement().primaryKey(), customerId: int("customerId").notNull(), version: int("version").notNull(), measurementsJson: json("measurementsJson").notNull(), fitPreference: varchar("fitPreference", { length: 100 }), collarStyle: varchar("collarStyle", { length: 100 }), pocketStyle: varchar("pocketStyle", { length: 100 }), notes: text("notes"), effectiveDate: date("effectiveDate").notNull(), createdBy: int("createdBy").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const tailoringOrders = mysqlTable("tailoringOrders", { id: int("id").autoincrement().primaryKey(), orderNumber: varchar("orderNumber", { length: 60 }).notNull().unique(), customerId: int("customerId").notNull(), measurementProfileId: int("measurementProfileId"), assignedTailorId: int("assignedTailorId"), garmentType: varchar("garmentType", { length: 80 }).notNull().default("Thoub"), quantity: int("quantity").notNull().default(1), status: mysqlEnum("status", ["draft", "confirmed", "cutting", "stitching", "fitting", "ready", "handed_over", "cancelled"]).notNull().default("draft"), dueDate: date("dueDate"), price: decimal("price", { precision: 12, scale: 3 }).notNull().default("0"), notes: text("notes"), productionNotes: text("productionNotes"), createdBy: int("createdBy").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const inventoryItems = mysqlTable("inventoryItems", { id: int("id").autoincrement().primaryKey(), code: varchar("code", { length: 60 }).notNull().unique(), name: varchar("name", { length: 160 }).notNull(), category: mysqlEnum("category", ["fabric", "lining", "buttons", "thread", "accessory", "other"]).notNull(), color: varchar("color", { length: 60 }), widthInches: decimal("widthInches", { precision: 10, scale: 2 }), unit: varchar("unit", { length: 40 }).notNull().default("Meters"), quantity: decimal("quantity", { precision: 12, scale: 3 }).notNull().default("0"), minThreshold: decimal("minThreshold", { precision: 12, scale: 3 }).notNull().default("0"), costPerUnit: decimal("costPerUnit", { precision: 12, scale: 3 }).notNull().default("0"), isActive: boolean("isActive").notNull().default(true), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const stockMovements = mysqlTable("stockMovements", { id: int("id").autoincrement().primaryKey(), inventoryItemId: int("inventoryItemId").notNull(), movementType: mysqlEnum("movementType", ["opening", "adjustment", "sale", "return", "purchase"]).notNull(), quantityChange: decimal("quantityChange", { precision: 12, scale: 3 }).notNull(), quantityBefore: decimal("quantityBefore", { precision: 12, scale: 3 }).notNull(), quantityAfter: decimal("quantityAfter", { precision: 12, scale: 3 }).notNull(), referenceType: varchar("referenceType", { length: 40 }), referenceId: int("referenceId"), notes: text("notes"), createdBy: int("createdBy"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const services = mysqlTable("services", { id: int("id").autoincrement().primaryKey(), sku: varchar("sku", { length: 60 }).notNull().unique(), name: varchar("name", { length: 160 }).notNull(), category: mysqlEnum("category", ["tailoring", "fabric", "alteration", "accessory", "other"]).notNull(), description: text("description"), unitPrice: decimal("unitPrice", { precision: 12, scale: 3 }).notNull(), inventoryItemId: int("inventoryItemId"), defaultFabricMeters: decimal("defaultFabricMeters", { precision: 12, scale: 3 }), isActive: boolean("isActive").notNull().default(true), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const sales = mysqlTable("sales", { id: int("id").autoincrement().primaryKey(), saleNumber: varchar("saleNumber", { length: 60 }).notNull().unique(), customerId: int("customerId"), customerNameSnapshot: varchar("customerNameSnapshot", { length: 160 }).notNull(), customerPhoneSnapshot: varchar("customerPhoneSnapshot", { length: 50 }), subtotal: decimal("subtotal", { precision: 12, scale: 3 }).notNull(), discount: decimal("discount", { precision: 12, scale: 3 }).notNull().default("0"), total: decimal("total", { precision: 12, scale: 3 }).notNull(), paymentMethod: mysqlEnum("paymentMethod", ["cash", "benefitpay", "bank_transfer", "credit_card"]).notNull(), paymentStatus: mysqlEnum("paymentStatus", ["paid", "partial", "unpaid"]).notNull().default("paid"), createdBy: int("createdBy").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const saleItems = mysqlTable("saleItems", { id: int("id").autoincrement().primaryKey(), saleId: int("saleId").notNull(), serviceId: int("serviceId"), inventoryItemId: int("inventoryItemId"), nameSnapshot: varchar("nameSnapshot", { length: 160 }).notNull(), quantity: decimal("quantity", { precision: 12, scale: 3 }).notNull(), unitPrice: decimal("unitPrice", { precision: 12, scale: 3 }).notNull(), lineTotal: decimal("total", { precision: 12, scale: 3 }).notNull(), assignedTailorId: int("assignedTailorId"), measurementProfileId: int("measurementProfileId") });
export const invoices = mysqlTable("invoices", { id: int("id").autoincrement().primaryKey(), saleId: int("saleId").notNull().unique(), invoiceNumber: varchar("invoiceNumber", { length: 60 }).notNull().unique(), status: mysqlEnum("status", ["paid", "partial", "unpaid", "void"]).notNull(), issuedAt: timestamp("issuedAt").defaultNow().notNull(), dueDate: date("dueDate"), notes: text("notes") });
export const staffProfiles = mysqlTable("staffProfiles", { id: int("id").autoincrement().primaryKey(), userId: int("userId"), name: varchar("name", { length: 160 }).notNull(), phone: varchar("phone", { length: 50 }), jobTitle: varchar("jobTitle", { length: 100 }).notNull(), baseSalary: decimal("baseSalary", { precision: 12, scale: 3 }).notNull(), commissionRate: decimal("commissionRate", { precision: 8, scale: 3 }).notNull().default("0"), isActive: boolean("isActive").notNull().default(true), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const attendance = mysqlTable("attendance", { id: int("id").autoincrement().primaryKey(), staffProfileId: int("staffProfileId").notNull(), workDate: date("workDate").notNull(), status: mysqlEnum("status", ["present", "absent", "leave", "half_day"]).notNull(), notes: text("notes"), recordedBy: int("recordedBy").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const performanceRecords = mysqlTable("performanceRecords", { id: int("id").autoincrement().primaryKey(), staffProfileId: int("staffProfileId").notNull(), workDate: date("workDate").notNull(), metric: varchar("metric", { length: 120 }).notNull(), units: decimal("units", { precision: 12, scale: 3 }).notNull(), commissionEarned: decimal("commissionEarned", { precision: 12, scale: 3 }).notNull().default("0"), notes: text("notes"), recordedBy: int("recordedBy").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const salaryPayouts = mysqlTable("salaryPayouts", { id: int("id").autoincrement().primaryKey(), staffProfileId: int("staffProfileId").notNull(), payPeriod: varchar("payPeriod", { length: 20 }).notNull(), baseSalary: decimal("baseSalary", { precision: 12, scale: 3 }).notNull(), performanceBonus: decimal("performanceBonus", { precision: 12, scale: 3 }).notNull().default("0"), deductions: decimal("deductions", { precision: 12, scale: 3 }).notNull().default("0"), netSalary: decimal("netSalary", { precision: 12, scale: 3 }).notNull(), notes: text("notes"), approvedBy: int("approvedBy").notNull(), paidAt: timestamp("paidAt").defaultNow().notNull() });
export const auditLogs = mysqlTable("auditLogs", { id: int("id").autoincrement().primaryKey(), actorId: int("actorId").notNull(), action: varchar("action", { length: 100 }).notNull(), entityType: varchar("entityType", { length: 80 }).notNull(), entityId: int("entityId"), detailsJson: text("detailsJson"), createdAt: timestamp("createdAt").defaultNow().notNull() });
