import { useState } from "react";
import { Edit3, Loader2, Plus, ShieldCheck, UserCog } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

const permissions = [{ value: "dashboard", label: "Owner dashboard", detail: "Review revenue, stock, and operating metrics." }, { value: "customers", label: "Customers & measurements", detail: "Maintain client records and fittings." }, { value: "sales", label: "Point of sale & invoices", detail: "Complete counter sales and print invoices." }, { value: "inventory", label: "Inventory control", detail: "Maintain materials and record stock adjustments." }, { value: "production", label: "Bespoke production", detail: "Create and update thoub orders through fitting and handover." }, { value: "payroll", label: "Workforce & payroll", detail: "Manage attendance, production, and payouts." }] as const;
type Permission = (typeof permissions)[number]["value"];
const busy = <div className="flex min-h-[280px] items-center justify-center text-muted-foreground"><Loader2 className="mr-2 h-5 w-5 animate-spin" />Loading owner settings…</div>;

function RoleForm({ role, onSave, pending }: { role?: { id: number; name: string; description: string | null; permissions: string[]; isActive: boolean }; onSave: (value: { name: string; description: string; permissions: Permission[]; isActive: boolean }) => void; pending: boolean }) {
  return <form className="space-y-4" onSubmit={event => { event.preventDefault(); const f = new FormData(event.currentTarget); const selected = permissions.filter(permission => f.get(permission.value) === "on").map(permission => permission.value); if (!selected.length) { toast.error("Choose at least one permission for this role."); return; } onSave({ name: String(f.get("name")), description: String(f.get("description") || ""), permissions: selected, isActive: f.get("isActive") === "on" }); }}><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1.5"><Label htmlFor="role-name">Role name</Label><Input id="role-name" name="name" defaultValue={role?.name || ""} placeholder="e.g. Counter supervisor" required /></div><div className="flex items-end"><label className="mb-2 flex items-center gap-2 text-sm"><input name="isActive" type="checkbox" defaultChecked={role?.isActive ?? true} />Role is active</label></div></div><div className="space-y-1.5"><Label htmlFor="role-description">Purpose</Label><Textarea id="role-description" name="description" defaultValue={role?.description || ""} placeholder="Describe who should receive this role." /></div><div className="space-y-2"><Label>Permissions</Label>{permissions.map(permission => <label key={permission.value} className="flex cursor-pointer gap-3 rounded-xl border p-3 hover:bg-muted/40"><input name={permission.value} type="checkbox" defaultChecked={role?.permissions.includes(permission.value)} className="mt-1" /><span><span className="block font-medium">{permission.label}</span><span className="mt-0.5 block text-xs text-muted-foreground">{permission.detail}</span></span></label>)}</div><Button className="w-full" disabled={pending}>{role ? "Save role" : "Create role"}</Button></form>;
}

export default function OwnerSettings() {
  const [createOpen, setCreateOpen] = useState(false); const [editingRoleId, setEditingRoleId] = useState<number | null>(null);
  const shop = trpc.erp.shop.get.useQuery(); const users = trpc.erp.team.listRoles.useQuery(); const roles = trpc.erp.team.listCustomRoles.useQuery(); const utils = trpc.useUtils();
  const refresh = () => { utils.erp.team.listRoles.invalidate(); utils.erp.team.listCustomRoles.invalidate(); };
  const saveShop = trpc.erp.shop.save.useMutation({ onSuccess: () => { utils.erp.shop.get.invalidate(); toast.success("Shop profile saved"); }, onError: error => toast.error(error.message) });
  const createRole = trpc.erp.team.createCustomRole.useMutation({ onSuccess: () => { refresh(); setCreateOpen(false); toast.success("Owner-managed role created"); }, onError: error => toast.error(error.message) });
  const updateRole = trpc.erp.team.updateCustomRole.useMutation({ onSuccess: () => { refresh(); setEditingRoleId(null); toast.success("Role updated"); }, onError: error => toast.error(error.message) });
  const assignRole = trpc.erp.team.assignCustomRole.useMutation({ onSuccess: () => { refresh(); toast.success("Role assignment saved"); }, onError: error => toast.error(error.message) });
  const clearRole = trpc.erp.team.clearCustomRole.useMutation({ onSuccess: () => { refresh(); toast.success("Custom role removed; the user returns to their legacy access profile."); }, onError: error => toast.error(error.message) });
  if (shop.isLoading || users.isLoading || roles.isLoading) return busy;
  if (shop.error || users.error || roles.error) return <p className="text-destructive">{shop.error?.message || users.error?.message || roles.error?.message}</p>;
  const editingRole = roles.data?.find(role => role.id === editingRoleId);
  return <div className="mx-auto max-w-6xl space-y-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-primary">Owner control centre</p><h1 className="mt-2 text-3xl font-semibold">Shop settings & access</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">Create the roles your business needs, choose their operational permissions, and assign them to signed-in staff without IT intervention. The owner administrator remains protected.</p></div><Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogTrigger asChild><Button><Plus className="mr-2 h-4 w-4" />Create business role</Button></DialogTrigger><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>Create owner-managed role</DialogTitle><DialogDescription>Choose only the operational areas this role needs.</DialogDescription></DialogHeader><RoleForm pending={createRole.isPending} onSave={value => createRole.mutate(value)} /></DialogContent></Dialog></div>
    <div className="grid gap-5 xl:grid-cols-[0.9fr_1.1fr]"><Card><CardHeader><CardTitle className="text-base">Business profile</CardTitle><CardDescription>Information printed on invoices and shown across the ERP.</CardDescription></CardHeader><CardContent><form className="space-y-3" onSubmit={event => { event.preventDefault(); const f = new FormData(event.currentTarget); saveShop.mutate({ shopName: String(f.get("shopName")), arabicShopName: String(f.get("arabicShopName") || ""), crNumber: String(f.get("crNumber") || ""), currency: "BHD", phone: String(f.get("phone") || ""), email: String(f.get("email") || ""), address: String(f.get("address") || ""), invoicePrefix: String(f.get("invoicePrefix")) }); }}><div className="space-y-1.5"><Label>Shop name</Label><Input name="shopName" defaultValue={shop.data?.shopName || ""} required /></div><div className="space-y-1.5"><Label>Arabic shop name</Label><Input name="arabicShopName" defaultValue={shop.data?.arabicShopName || ""} /></div><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1.5"><Label>Commercial registration</Label><Input name="crNumber" defaultValue={shop.data?.crNumber || ""} /></div><div className="space-y-1.5"><Label>Invoice prefix</Label><Input name="invoicePrefix" defaultValue={shop.data?.invoicePrefix || "INV"} required /></div></div><div className="space-y-1.5"><Label>Phone</Label><Input name="phone" defaultValue={shop.data?.phone || ""} /></div><div className="space-y-1.5"><Label>Email</Label><Input name="email" type="email" defaultValue={shop.data?.email || ""} /></div><div className="space-y-1.5"><Label>Business address</Label><Textarea name="address" defaultValue={shop.data?.address || ""} /></div><Button disabled={saveShop.isPending}>Save shop profile</Button></form></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ShieldCheck className="h-4 w-4 text-primary" />Role library</CardTitle><CardDescription>Roles are created and controlled by the business owner. Deactivate a role to stop new assignments while preserving its audit history.</CardDescription></CardHeader><CardContent className="space-y-3">{roles.data?.length === 0 ? <div className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground">No custom roles yet. Create roles such as Counter Supervisor, Stock Controller, or Payroll Officer.</div> : roles.data?.map(role => <div key={role.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{role.name}</p><p className="mt-1 text-sm text-muted-foreground">{role.description || "No description provided."}</p></div><div className="flex items-center gap-2"><Badge variant={role.isActive ? "secondary" : "outline"}>{role.isActive ? "Active" : "Inactive"}</Badge><Button size="sm" variant="outline" onClick={() => setEditingRoleId(role.id)}><Edit3 className="mr-1.5 h-3.5 w-3.5" />Edit</Button></div></div><div className="mt-3 flex flex-wrap gap-1.5">{role.permissions.map(permission => <Badge key={permission} variant="outline" className="capitalize">{permission.replace("_", " ")}</Badge>)}</div></div>)}</CardContent></Card></div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><UserCog className="h-4 w-4 text-primary" />Assign owner-managed roles</CardTitle><CardDescription>Custom roles override standard operational access for non-owner users. Remove an assignment to restore the user’s legacy profile.</CardDescription></CardHeader><CardContent className="space-y-3">{users.data?.length === 0 ? <p className="text-sm text-muted-foreground">Team members will appear after they sign in once.</p> : users.data?.map(user => <form key={user.userId} className="flex flex-col justify-between gap-3 rounded-xl border p-4 sm:flex-row sm:items-center" onSubmit={event => { event.preventDefault(); const f = new FormData(event.currentTarget); const roleId = Number(f.get("customRoleId")); if (!roleId) { clearRole.mutate({ userId: user.userId }); return; } assignRole.mutate({ userId: user.userId, customRoleId: roleId, isActive: f.get("isActive") === "on" }); }}><div className="min-w-0"><p className="font-semibold">{user.name || `User #${user.userId}`}</p><p className="mt-1 truncate text-xs text-muted-foreground">{user.email || `Signed-in user #${user.userId}`}</p><p className="mt-1 text-xs text-muted-foreground">Current access: {user.customRoleName ? `${user.customRoleName}${user.customRoleActive ? "" : " (inactive)"}` : user.businessRole}</p></div><div className="flex flex-wrap items-center gap-2"><select name="customRoleId" defaultValue={user.customRoleId ? String(user.customRoleId) : ""} className="h-10 min-w-[180px] rounded-md border bg-white px-3 text-sm"><option value="">Use legacy profile</option>{roles.data?.filter(role => role.isActive).map(role => <option key={role.id} value={role.id}>{role.name}</option>)}</select><label className="flex items-center gap-1 text-xs"><input name="isActive" type="checkbox" defaultChecked={user.customRoleActive} />Active</label><Button size="sm" variant="outline" disabled={assignRole.isPending || clearRole.isPending}>Save access</Button></div></form>)}</CardContent></Card>
    <Dialog open={!!editingRole} onOpenChange={open => !open && setEditingRoleId(null)}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>Edit role</DialogTitle><DialogDescription>Changes apply to all active assignees immediately.</DialogDescription></DialogHeader>{editingRole && <RoleForm role={editingRole} pending={updateRole.isPending} onSave={value => updateRole.mutate({ id: editingRole.id, ...value })} />}</DialogContent></Dialog>
  </div>;
}
